sponsor:
  allow_ask_for_volunteers: false
  barcode_prefix: "RTV"
  name: "Rock the Vote"
  url: "http://www.rockthevote.com"
  facebook_callback_url: <%= CGI.escape("http://www.rockthevote.com/register/fb") %>
  partner_signup_url: "http://www.rockthevote.com/partner"
  footer_link_base_url: "http://www.rockthevote.com/voter-registration/online-application-system"
  footer_copyright: "&copy; Copyright %d, Rock the Vote"
  partner_comarketing_text: |
    Numbers not as high as you'd like?
    <a href="http://www.rockthevote.com/partner/how-to-get-it-out-there.html" target="_blank">Here are some ways to help market your tool.</a>

from_address: "rocky@example.com"
default_url_host: "register.example.com"
ui_url_host: "register5.example.com"

skip_survey_and_opt_ins: true

admin:
  from_address: "rtv-admins@osuosl.org"
  translation_recipients: "david@rockthevote.com, alex.mekelburg@gmail.com"

admin_username: 'admin'
widget_js_url:  'https://s3.amazonaws.com/ovr/widget_loader.js'

use_https: false
paperclip_options: 
  storage: "fog"
  path: ":rails_root/public/system/:attachment/:id/:style/:filename"
  url: "/system/:attachment/:id/:style/:filename"

mobile_redirect_url: http://stage-rocky.ctacdev.com/
mobile_browsers:
  - mobile
  - webos
  - blackberry
  - iphone
  
widget_loader_url: https://s3.amazonaws.com/ovr/widget_loader.js
hours_before_first_reminder: 120
hours_between_first_and_second_reminder: 72
pdf_expiration_days: 14
pdf_no_email_expiration_minutes: 10
partner_csv_expiration_minutes: 30

  
ovr_states:
  CA:
    redirect_to_online_reg_url: true
    api_settings:
      api_url: https://covrapitest.sos.ca.gov/PostingEntityInterfaceService.svc
      api_key: d2DE1Nht8I
      api_posting_entity_name: RTV
      debug_in_ui: false
      log_all_requests: false
      disclosures_url: https://a8e83b219df9c88311b3-01fbb794ac405944f26ec8749fe8fe7b.ssl.cf1.rackcdn.com/discl/
      web_url_base: https://covrtest.sos.ca.gov
      web_agency_key: RTV
      custom_error_string: CUSTOM_COVR_ERROR
    languages:
      - en
      - es
      - zh-tw
      - vi
      - ko
      - tl
      - ja
      - hi
      - km
      - th
  NV:
    redirect_to_online_reg_url: true
    languages:
      - en
  WA:
    languages:
      - en

  
enabled_locales:
  - en
  - es


redirect_ovr_states:
  AZ:
    EN: Arizona EZ Voter Registration|https://servicearizona.com/webapp/evoter/selectLanguage
    ES: Registro Electoral EZ de Arizona|https://servicearizona.com/webapp/evoter/register?execution=e1s1
  CA:
    EN: California Online Voter Registration|http://registertovote.ca.gov/
    ES: Inscripción de votante en línea de California|http://registertovote.ca.gov/es/
  CO:
    EN: Colorado Online Voter Registration|https://www.sos.state.co.us/voter-classic/secuRegVoterIntro.do
  CT:
    EN: Connecticut Online Voter Registration|https://voterregistration.ct.gov/OLVR/welcome.do
    ES: Inscripción en el Padrón Electoral https://voterregistration.ct.gov/OLVR/prefix.do
  DE:
    EN: Delaware Online Voter Registration|https://ivote.de.gov/
  GA:
    EN: Georgia Online Voter Registration|https://registertovote.sos.ga.gov/GAOLVR/welcome.do
  HI:
    EN: Hawaii Online Voter Registration System|https://olvr.hawaii.gov/
  IL:
    EN: Illinois Online Voter Registration|https://ova.elections.il.gov/RegistrationClosed.aspx
    ES: Registro electoral de Illinois|https://spanish-ova.elections.il.gov/RegistrationClosed.aspx
  IN:
    EN: Indiana Online Voter Registration|https://indianavoters.in.gov/PublicSite/OVR/Introduction.aspx
  KS:
    EN: Kansas Online Voter Registration|https://www.kdor.org/voterregistration/Default.aspx
  LA:
    EN: Louisiana Online Voter Registration|http://www.sos.la.gov/ElectionsAndVoting/Pages/OnlineVoterRegistration.aspx
  MD:
    EN: Maryland Online Voter Registration|https://voterservices.elections.state.md.us/OnlineVoterRegistration/VoterType
    ES: Registro de votante|https://voterservices.elections.state.md.us/OnlineVoterRegistration/VoterType
  MO:
    EN: Missouri Online Voter Registration|http://s1.sos.mo.gov/elections/goVoteMissouri/register.aspx
  MN:
    EN: Minnesota Online Voter Registration|https://mnvotes.sos.state.mn.us/VoterRegistration/VoterRegistrationStep1.aspx
  MA:
    EN: Massachusetts Online Voter Registration System|https://www.sec.state.ma.us/ovr/
  NE:
    EN: Nebraska Online Voter Registration|https://www.nebraska.gov/apps-sos-voter-registration/
    ES: Registrarse para votar en Nebraska|https://www.nebraska.gov/apps-sos-voter-registration/?lang=es
  NV:
    EN: Nevada Online Voter Registration|https://nvsos.gov/sosvoterservices/Registration/step1.aspx
    ES: Inscripción de votates en línea|https://nvsos.gov/sosvoterservices/Registration/step1.aspx
  NY:
    EN: New York State Voter Registration Form|http://www.elections.ny.gov/NYSBOE/download/voting/voteform_enterable.pdf
  PA:
    EN: PA Online Voter Registration|https://www.pavoterservices.state.pa.us/Pages/VoterRegistrationApplication.aspx
  OR:
    EN: Oregon Online Voter Registration|https://secure.sos.state.or.us/orestar/vr/register.do?lang=eng&source=SOS
    ES: Mi voto|https://secure.sos.state.or.us/orestar/vr/register.do?lang=spa#
  SC:
    EN: South Carolina Online Voter Registration|https://info.scvotes.sc.gov/eng/ovr/start.aspx
  UT:
    EN: Utah Online Voter Registration|https://secure.utah.gov/voterreg/index.html
  VA:
    EN: Virginia Online Voter Registration|https://www.vote.virginia.gov/
  VT:
    EN: Vermont Online Voter Registration|http://olvr.sec.state.vt.us/
  WA:
    EN: Washington Online Voter Registration|http://www.sos.wa.gov/elections/myvote/
    ES: MyVote|http://www.sos.wa.gov/elections/myvote/
  WV:
    EN: West Virginia Online Voter Registration|https://ovr.sos.wv.gov/Register
pdf:
  nvra:
    page1:
      default_logo: 'pdf/rtvlogo.gif'
      other_block:
        instructions_url: "http://www.rockthevote.com/registration/instructions/<STATE>-<LOCALE>.html"
  
